version: "3"

services:
  backend:
    image: backend
    container_name: backend
    build: .
    user: appuser
    ports:
      - 8000:8000
    volumes:
      - ./service:/app
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    hostname: $${POSTGRES_HOST}
    container_name: database
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 8001:5432
    volumes:
      - database:/var/lib/postgresql/data


volumes:
  database:
